import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { ScriptProps } from 'next/script'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

// export async function getStaticPaths(){
//   const user = await fetch(`https://e-commerce-cbe7c-default-rtdb.firebaseio.com/products.json`)

//   const userData = await user.json()

//   return {

//     props: { paths: userData.map((el:any,index:number)=>{params:{index:index}}) ,fallback:false}
//   }
// }

export default function Home({ userIndexes }: any) {
  console.log(userIndexes.map((el: any, index: number) =>  ( { params: { index: index } })))
console.log(userIndexes)
console.log(userIndexes.map((el: any, index: number) => ({ params: { index: index } })))
console.log(userIndexes.map((el:any,index:number)=>{
  console.log(index)
}))
  return (
    <>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        {/* <div>
     {users.map((el:any)=>el.imageTitle)}

    </div> */}
 {
        userIndexes.map((el: any,id:number) =>
          <Link key={id} href={`/users/${id}`}>{id}</Link>
        )
      }
      </main>
    </>
  )
}



export async function getStaticProps() {
  const user = await fetch(`https://e-commerce-cbe7c-default-rtdb.firebaseio.com/products.json`)

  const userIndexes = await user.json()
  console.log(userIndexes.map((el: any, index: number) => { return { params: { index: index } } }))

  return { props: { userIndexes: userIndexes } }
}